<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HotelsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $hotels = [
            [
                'location_id' => 1,
                'locality_id' => 1,
                'name' => 'The Taj Mahal Palace',
                'description' => 'Luxury hotel with views of the Arabian Sea.',
                'rating_avg' => 4.8,
                'review_count' => 2500,
                'is_featured' => true,
                'latitude' => 18.9218,
                'longitude' => 72.8333,
                'property_rules' => 'No smoking. Check-in after 2 PM. No pets allowed.',
                'address' => 'Apollo Bunder, Colaba, Mumbai, Maharashtra 400001',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_id' => 1,
                'locality_id' => 2,
                'name' => 'The Oberoi Mumbai',
                'description' => 'High-end hotel near Marine Drive.',
                'rating_avg' => 4.7,
                'review_count' => 1800,
                'is_featured' => true,
                'latitude' => 18.9220,
                'longitude' => 72.8296,
                'address' => 'Nariman Point, Mumbai, Maharashtra 400021',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_id' => 2,
                'locality_id' => 3,
                'name' => 'The Imperial, New Delhi',
                'description' => 'Heritage hotel in the heart of Delhi.',
                'rating_avg' => 4.5,
                'review_count' => 1600,
                'is_featured' => false,
                'latitude' => 28.6315,
                'longitude' => 77.2167,
                'address' => 'Janpath Lane, Connaught Place, New Delhi, Delhi 110001',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_id' => 3,
                'locality_id' => 5,
                'name' => 'ITC Gardenia, Bangalore',
                'description' => 'Luxury hotel with garden views.',
                'rating_avg' => 4.6,
                'review_count' => 1400,
                'is_featured' => true,
                'latitude' => 13.0358,
                'longitude' => 77.5732,
                'address' => 'No.1, Residency Road, Bangalore, Karnataka 560025',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_id' => 4,
                'locality_id' => 7,
                'name' => 'The Leela Palace Chennai',
                'description' => 'Upscale beachside hotel.',
                'rating_avg' => 4.7,
                'review_count' => 1200,
                'is_featured' => true,
                'latitude' => 13.0322,
                'longitude' => 80.2780,
                'address' => 'Kamaraj Salai, MRC Nagar, Chennai, Tamil Nadu 600028',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_id' => 5,
                'locality_id' => 9,
                'name' => 'The Oberoi Grand, Kolkata',
                'description' => 'Elegant hotel in central Kolkata.',
                'rating_avg' => 4.6,
                'review_count' => 1300,
                'is_featured' => false,
                'latitude' => 22.5650,
                'longitude' => 88.3432,
                'address' => '15 Jawaharlal Nehru Rd, Kolkata, West Bengal 700013',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // NEW HOTELS
            [
                'location_id' => 3,
                'locality_id' => 5,
                'name' => 'JW Marriott Hotel Pune',
                'description' => 'Modern luxury hotel with mountain views.',
                'rating_avg' => 4.6,
                'review_count' => 1100,
                'is_featured' => true,
                'latitude' => 18.5204,
                'longitude' => 73.8567,
                'address' => 'Senapati Bapat Rd, Pune, Maharashtra 411053',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                 'location_id' => 3,
                'locality_id' => 5,
                'name' => 'Taj Falaknuma Palace, Hyderabad',
                'description' => 'Lavish palace hotel with historical charm.',
                'rating_avg' => 4.9,
                'review_count' => 950,
                'is_featured' => true,
                'latitude' => 17.3302,
                'longitude' => 78.4678,
                'address' => 'Engine Bowli, Falaknuma, Hyderabad, Telangana 500053',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                 'location_id' => 3,
                'locality_id' => 5,
                'name' => 'Le Meridien Jaipur Resort & Spa',
                'description' => 'Luxury resort surrounded by Aravalli hills.',
                'rating_avg' => 4.4,
                'review_count' => 850,
                'is_featured' => false,
                'latitude' => 26.9124,
                'longitude' => 75.7873,
                'address' => 'Number 1, RIICO, Kukas, Jaipur, Rajasthan 302028',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                 'location_id' => 3,
                'locality_id' => 5,
                'name' => 'Vivanta Dal View, Srinagar',
                'description' => 'Scenic hotel overlooking Dal Lake.',
                'rating_avg' => 4.5,
                'review_count' => 780,
                'is_featured' => true,
                'latitude' => 34.1016,
                'longitude' => 74.8334,
                'address' => 'Kralsangri, Brein, Srinagar, Jammu and Kashmir 191121',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_id' => 3,
                'locality_id' => 5,
                'name' => 'Alila Diwa Goa',
                'description' => 'Upscale resort near Gonsua Beach.',
                'rating_avg' => 4.6,
                'review_count' => 890,
                'is_featured' => true,
                'latitude' => 15.2752,
                'longitude' => 73.9601,
                'address' => '48/10, Adao Waddo, Majorda, Goa 403713',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                 'location_id' => 3,
                'locality_id' => 5,
                'name' => 'The Tamara Coorg',
                'description' => 'Eco-resort nestled in Coorg’s hills.',
                'rating_avg' => 4.7,
                'review_count' => 720,
                'is_featured' => false,
                'latitude' => 12.3874,
                'longitude' => 75.7382,
                'address' => 'Kabbinakad Estate, Yevakapadi, Napoklu Nad, Madikeri, Karnataka 571212',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($hotels as $hotel) {
            DB::table('hotels')->insert($hotel);
        }
    }
}
